@Backend_HostAddress = http://localhost:5110

GET {{Backend_HostAddress}}/test/
Accept: application/json

###

GET {{Backend_HostAddress}}/brand/

###

POST {{Backend_HostAddress}}/brand/
Content-Type: application/json

{
  "name":"Marca app"
}

###

PUT {{Backend_HostAddress}}/brand/5
Content-Type: application/json

{
  "name":"Marca modificada"
}

###

DELETE {{Backend_HostAddress}}/brand/7
